gender_model_1:
  model_type: "keyword_model"
  model_settings:
    case_sensitive: False
    target: "author_name"
  model_data:
    files:
      - "rules/author_name_keyword.pkl"

#gender_model_2:
#  model_type: "rule_model"
#  model_settings:
#    target: "content"
#  model_data:
#    female:
#      dirs:
#        - "Rules/Gender/Female/Regex"
#    male:
#      files:
#        - "Rules/Gender/Male/Regex/maleRegex.txt"

