settings:
  database:
    author_cache: 1000
    document_batch: 1000
    fetch_limit: -1
    connect_timeout: 30
    connect_retries: 1

  logger:
    logging_fmt: "[%(asctime)s][{_context}][%(levelname)s]: %(message)s"
    logging_fmt_err: "[%(asctime)s][{_context}][%(funcName)s()][%(levelname)s]: %(message)s"
    log_backup_count: 30  # days

  content:
    stopwords:
      files:
        - "files/stopWords.txt"
    blacklist_patterns:
      files:
        -
    min_doc_length: 1
    max_doc_length: 2000

  compare_file:
    files:
      forum: "files/forum_convert.xlsx"
      social: "files/social_convert.xlsx"
      comment: "files/comment_convert.xlsx"
      qa: "files/qa_convert.xlsx"
      blog: "files/blog_convert.xlsx"
      news: "files/news_convert.xlsx"
